[client]
# Controls whether to display the default sidebar page navigation in a
# multi-page app. This only applies when app's pages are defined by the
# `pages/` directory.
#
# Default: true
showSidebarNavigation = false
toolbarMode = "minimal"

[theme]
primaryColor="#0052FF"          # Color for interactive elements and highlights (old: 306bea)
backgroundColor="#FFFFFF"        # Main app background color
secondaryBackgroundColor="#F1F3F4" # Color for sidebars, code blocks, etc. (original F0F2F6)
textColor="#202124"              # Default text color
font="sans serif"                # Base font (sans serif, serif, or monospace)
linkColor = "#202124"

[theme.sidebar]
# This specifically targets text color in the sidebar
textColor = "#202124"
linkColor = "#202124"
linkUnderline = false